name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        cd frontend-expo
        npm install

    - name: Build Project
      run: |
        cd frontend-expo
        npm run build:web

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: "root"
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        # Save SSH private key to a file
        echo "$SSH_PRIVATE_KEY" > /tmp/private_key
        chmod 600 /tmp/private_key

        # Transfer the frontend build files to the server
        rsync -avz -e "ssh -i /tmp/private_key -o StrictHostKeyChecking=no" frontend-expo/web-build/ ${SERVER_USER}@${SERVER_IP}:/var/www/frontend-expo/

        # Update app.json on the server
        ssh -i /tmp/private_key -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} \
        "sed -i \"s|\\\"API_URL\\\": \\\"http://localhost:8888/public\\\"|\\\"API_URL\\\": \\\"http://${SECRETS_SERVER_IP}/service\\\"|\" /var/www/frontend-expo/app.json"
      
        # Update .env on the server
        ssh -i /tmp/private_key -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} \
        "sed -i \"s|^EXPO_PUBLIC_URL=.*|EXPO_PUBLIC_URL=http://${SECRETS_SERVER_IP}/service|\" /var/www/frontend-expo/.env"




        # Cleanup
        rm /tmp/private_key
